### PR TITLE
B0 Ecal threshold

### PR DESCRIPTION
**Pull request by kkauder**
### Briefly, what does this PR introduce?
Updated B0ECAL threshold from the [digitization table from 10/2](https://brookhavenlab.sharepoint.com/:x:/s/EICPublicSharingDocs/EeICxMJ9vGtPtyq5g4qzcSwBKCqkHDj06KDdSvYQ7pxqrQ?rtime=lD_5kMnT20g).

### Notes:
- This uses a cut on accumulated energy.
- Previous adc cut settings are inconsistent, at most one of `.thresholdFactor`  and `.thresholdValue` should be non-zero. I therefore turned off zero suppression for this campaign. We can make the ADC cut more consistent, or replace the energy cut with it, in the future.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #895 )
- [ ] New feature (issue #__)
- [ ] Documentation update
- [x] Other: Maintenance

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
Yes.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### CODE REVIEW

**Comment by kkauder** [comment]
@ajentsch Sorry for the late ping, if you can sign off on this (make sure it's not wrong!) asap, it can go into the November campaign.

**Comment by ajentsch** [comment]
> @ajentsch Sorry for the late ping, if you can sign off on this (make sure it's not wrong!) asap, it can go into the November campaign.

@michael-pitt should be the one to take a look at this to ensure it's correct - but it matches the table.

**Comment by kkauder** [comment]
@michael-pitt Can you please check and approve if appropriate?

**Comment by michael-pitt** [comment]
Hi @kkauder @ajentsch 

I've tested the new branch and attached the energy response of B0ECAL for photons in the energy range of up to 100 GeV within B0ECAL acceptance: [B0ECAL_responce_branch.pdf](https://github.com/eic/EICrecon/files/13319017/B0ECAL_responce_branch.pdf)

The new fix removes clusters with very low energy but doesn't change the detector response, so I will approve the fix.

There is an issue with energy response for photons above 40 GeV, but it was also observed with the nightly, probably caused by an earlier update.

@kkauder, maybe we should also update https://github.com/eic/EICrecon/blob/main/src/detectors/ZDC/ZDC.cc?

Regards,
Michael

**Review by michael-pitt — APPROVED** [review]

**Comment by kkauder** [comment]
Thank you for the thorough review!!

**Comment by kkauder** [comment]
@michael-pitt , regarding the ZDC I agree but there are four technologies and I didn't know which one to update. If you can give me a little guidance (maybe in a separate email), I can work on that as well

**Pull request merged**
