### PR TITLE
ScatteredElectronsEMinusPz: refactor to use algorithms interface and ParticleSvc

### PR DESCRIPTION
**Pull request by veprbl**
### Briefly, what does this PR introduce?
Refactor to use algorithms interface and ParticleSvc.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Review by wdconinc — APPROVED** [review]
Thanks! I've been wanting to convert the remaining ones!

**Comment by veprbl** [comment]
There are others left!

**Review by wdconinc — APPROVED** [review]
Still good

**Comment by veprbl** [comment]
There was a small regression, but this should be good now. Here is a comparison:
https://veprbl.github.io/capybara-reports/6ef26b367146db1d96413b38cd8e994d/

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
