### PR TITLE
Replace CalorimeterScFiDigi with CalorimeterHitDigi, implement merging at digi step

### PR DESCRIPTION
**Pull request by Chao1009**
### Briefly, what does this PR introduce?
It replaces the algorithm CalorimeterScFiDigi with CaloriemterHitDigi because the former breaks the production run of arches configuration.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #465)
- [x] New feature (issue #465)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [x] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
It should not affect the default use of CalorimeterHitDigi. However, it implements the merging at the digitization step, which can be enabled by using the required parameters.

### Does this PR change default behavior?
It should not affect the default use of CalorimeterHitDigi.

### CODE REVIEW

**Comment by Chao1009** [comment]
It's still in draft stage, testing on local copy now.

**Comment by wdconinc** [comment]
Added @veprbl for review, knowing this is still a draft.

**Comment by Chao1009** [comment]
It 's ready

**Comment by wdconinc** [comment]
File size certainly looks a lot better.
image

**Review by wdconinc — COMMENTED** [review]
Looks good to me. Waiting for @veprbl's approval.

**Comment by veprbl** [comment]
Please merge, if this is ready.

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
