### PR TITLE
fix: apply all automatic IWYU suggestions (and 2 fixes by hand)

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This applies all automatically suggested IWYU fixes after iwyu functionality in #755 and additional fixes in #1079.

Two fixes have to be applied by hand because iwyu does not have a pragma to keep a specific header before another header (needed due to upstream bugs):
- TrackSeeding.cc: include KDTree first until Acts v23.0.0
- TrackSeeding.h: include cstddef first until Acts v27.2.0

Since we are working on upgrading Acts, I think we can live with these two headers for the time being (which will show up as iwyu suggestions for anyone who edits those files, including this PR).

TODO:
- [x] merge #1079 first
- [x] rebase this branch

### What kind of change does this PR introduce?
- [x] Bug fix (issue: headers all over the place)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
Build time tests with `cmake -Bbuild -S. --fresh && time make -Cbuild -j8 install`.

### Before iwyu:
```
real    3m57.121s
user    24m11.211s
sys     1m36.770s
```

### After iwyu:
```
real    3m31.916s
user    22m1.922s
sys     1m26.855s
```

**Comment by wdconinc** [comment]
Rebased, one conflict resolved.

**Comment by wdconinc** [comment]
Put back `datamodel_inclues.h` with `IWYU pragma: keep` to fix data model-related compilation error.

**Comment by wdconinc** [comment]
No diffs in capybary, no further iwyu suggestion. This is ready for merging, as far as I am concerned.

**Review by veprbl — APPROVED** [review]
Diff LGTM, capybara happy

**Pull request merged**
