### PR TITLE
BHCAL: drop support for legacy sectors

### PR DESCRIPTION
**Pull request by veprbl**
This readout field was removed in 24.03.0. We don't need to support it.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by ruse-traveler** [comment]
pr1540capybara ncdis10x100minq0_craterlake recHits_posXvsY

Strange... I'm seeing some small diffs in the capybara 😕

**Review by ruse-traveler — COMMENTED** [review]
Just to check, will the full files for 2024.03.0 and earlier be removed from disk? This seems reasonable to me, but I hesitate slightly if there's the possibility of someone trying to run EICrecon on an earlier geometry...

**Comment by veprbl** [comment]
That version is already not packaged in the container:
https://github.com/eic/containers/blob/d9ec8f7e3c077fb053c442114686d28f65351b21/spack-environment/xl/spack.yaml#L31-L35

I believe, the small differences come from using different npsim simulations that are cached separately between the branch and the PR.

**Comment by ruse-traveler** [comment]
Ahhhh I see!

**Review by ruse-traveler — APPROVED** [review]
LGTM!

**Pull request merged**
