### PR TITLE
feat(ci): updates to lsan.supp and require PRs to pass leak checks

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Until now we had enough leaks that enforcing absence of memory leaks was not feasible. We have now fixes for the remaining memory leaks inside EICrecon:
- [x] #974 
- [x] #977 
  - [x] #981
  - [x] #982
  - [x] #983
- [x] #979 

The remaining memory leaks are external to EICrecon (though some are not exactly completely outside of our control either, e.g. https://github.com/eic/irt/issues/36), so we can suppress them and require any PRs to come back clean.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue: require clean leak sanitizer runs)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No. (If this breaks your code, then from now on your code is the thing that's broken.)

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
```
-----------------------------------------------------
Suppressions used:
  count      bytes template
    756      42336 CherenkovPID::AddMassHypothesis
    150      54000 dd4hep::DetElement::DetElement
      8       1856 dd4hep::Header::Header
  13107     314568 edm4hep::*::createBuffers
    591      74760 libCling.so
1581030   89715048 libCore.so
-----------------------------------------------------
```

I am not sure if the `lsan.supp` format allows for end-of-line comments but a link to an issue or PR for each of the suppression could be a nice expectations (maybe not feasible with ROOT libCore or libCling).

**Comment by wdconinc** [comment]
New leak, https://github.com/eic/EICrecon/actions/runs/6281200363/job/17059319402?pr=980#step:9:115. Is that something we should suppress or is it legitimately internal to our code base?

**Comment by wdconinc** [comment]
The memory leaks in ctest are (with edm4hep build in debug mode):
```
1: ==140637==ERROR: LeakSanitizer: detected memory leaks
1: 
1: Direct leak of 56 byte(s) in 1 object(s) allocated from:
1:     #0 0x5622eec662fd in operator new(unsigned long) (/home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/build/src/tests/algorithms_test/algorithms_test+0x10a2fd) (BuildId: cca01c5866a2601b6b03ea544eec2f0b1ba572b9)
1:     #1 0x7f279ebbd378 in edm4hep::CaloHitContribution::CaloHitContribution(int, float, float, edm4hep::Vector3f) /home/wdconinc/git/EDM4hep/edm4hep/src/CaloHitContribution.cc:22:38
1:     #2 0x5622eec79d00 in CATCH2_INTERNAL_TEST_0() /home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/src/tests/algorithms_test/calorimetry_CalorimeterHitDigi.cc:48:29
1:     #3 0x5622eecbbe0f in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (/home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/build/src/tests/algorithms_test/algorithms_test+0x15fe0f) (BuildId: cca01c5866a2601b6b03ea544eec2f0b1ba572b9)
1: 
1: Direct leak of 56 byte(s) in 1 object(s) allocated from:
1:     #0 0x5622eec662fd in operator new(unsigned long) (/home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/build/src/tests/algorithms_test/algorithms_test+0x10a2fd) (BuildId: cca01c5866a2601b6b03ea544eec2f0b1ba572b9)
1:     #1 0x7f279ebbd378 in edm4hep::CaloHitContribution::CaloHitContribution(int, float, float, edm4hep::Vector3f) /home/wdconinc/git/EDM4hep/edm4hep/src/CaloHitContribution.cc:22:38
1:     #2 0x5622eec79cb9 in CATCH2_INTERNAL_TEST_0() /home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/src/tests/algorithms_test/calorimetry_CalorimeterHitDigi.cc:42:29
1:     #3 0x5622eecbbe0f in Catch::RunContext::runCurrentTest(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&) (/home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/build/src/tests/algorithms_test/algorithms_test+0x15fe0f) (BuildId: cca01c5866a2601b6b03ea544eec2f0b1ba572b9)
1: 
1: SUMMARY: AddressSanitizer: 112 byte(s) leaked in 2 allocation(s).
```

**Comment by wdconinc** [comment]
If we are going to enforce lsan here, we need to enforce lsan on epic as well:
```
Direct leak of 56 byte(s) in 7 object(s) allocated from:
    #0 0x563c4c2d174d in operator new(unsigned long) (/home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/bin/eicrecon+0xef74d) (BuildId: 2b54114cacfdd33364d9d357152362df595c2256)
    #1 0x7f52f0fbcf08 in create_detector(dd4hep::Detector&, dd4hep::xml::Handle_t, dd4hep::SensitiveDetector) (.constprop.0) /tmp/det/src/magnetVacuumFF.cpp:206:97
    #2 0x7f52f0fbe553 in create /tmp/det/src/magnetVacuumFF.cpp:285:1
    #3 0x7f52f0fbe553 in (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::det_element_magnetElementInnerVacuum, dd4hep::NamedObject* (dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*)>::call(dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*) /usr/._local/peaynde2xk7vuv3gwcry6ymkqusjhbid/include/DD4hep/Factories.h:249:54

Direct leak of 48 byte(s) in 6 object(s) allocated from:
    #0 0x563c4c2d174d in operator new(unsigned long) (/home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/bin/eicrecon+0xef74d) (BuildId: 2b54114cacfdd33364d9d357152362df595c2256)
    #1 0x7f52f0fbd6ce in create_detector(dd4hep::Detector&, dd4hep::xml::Handle_t, dd4hep::SensitiveDetector) (.constprop.0) /tmp/det/src/magnetVacuumFF.cpp:233:97
    #2 0x7f52f0fbe553 in create /tmp/det/src/magnetVacuumFF.cpp:285:1
    #3 0x7f52f0fbe553 in (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::det_element_magnetElementInnerVacuum, dd4hep::NamedObject* (dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*)>::call(dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*) /usr/._local/peaynde2xk7vuv3gwcry6ymkqusjhbid/include/DD4hep/Factories.h:249:54

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x563c4c2d174d in operator new(unsigned long) (/home/wdconinc/git/EICrecon/.worktree/update-lsan-and-fail-on-new-leaks/bin/eicrecon+0xef74d) (BuildId: 2b54114cacfdd33364d9d357152362df595c2256)
    #1 0x7f52f0fbdd28 in create_detector(dd4hep::Detector&, dd4hep::xml::Handle_t, dd4hep::SensitiveDetector) (.constprop.0) /tmp/det/src/magnetVacuumFF.cpp:259:109
    #2 0x7f52f0fbe553 in create /tmp/det/src/magnetVacuumFF.cpp:285:1
    #3 0x7f52f0fbe553 in (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::det_element_magnetElementInnerVacuum, dd4hep::NamedObject* (dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*)>::call(dd4hep::Detector*, dd4hep::xml::Handle_t*, dd4hep::Handle<dd4hep::NamedObject>*) /usr/._local/peaynde2xk7vuv3gwcry6ymkqusjhbid/include/DD4hep/Factories.h:249:54
```

**Review by veprbl — DISMISSED** [review]

**Comment by wdconinc** [comment]
It will still fail but at least it won't require edits in this branch anymore.

**Comment by wdconinc** [comment]
This now passes checks. Not sure why the femc suppressions aren't triggered. It's possible that benchmark doesn't even get to the point of running any of the code that is obviously leaking.

**Comment by wdconinc** [comment]
The femc and lfhcal studies now pass lsan checks without suppression. Ready for approving review.

**Review by veprbl — APPROVED** [review]
Diff LGTM, and this is not ready for disapproving reviews

**Pull request merged**
