### PR TITLE
feat: fix compilation for Acts versions from v33 up to v35

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This adapts our tracking algorithms to any Acts version between v31 and v36 (to be released, so additional refactors may hit the Acts main branch that would need porting).

The commits in this branch are topologically ordered with reference to the commit message title, Acts PR number, and version validity. All commits compile individually, but no event-for-event validation has been performed.

The support for mulitple versions is done by somewhat extensive use of preprocessor directives based on `Acts_VERSION_MAJOR`.

Builds with:
- v32.1.0: https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/3481513#L3103
- v33.1.0: https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/3482111#L3549
- v34.1.0: https://eicweb.phy.anl.gov/containers/eic_container/-/jobs/3482134#L3699
- v35.0.0: locally, but not yet in eic_container since this requires #1520 and related eic-spack PRs first

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue: Acts versions are released faster than we can keep up with)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
The (short term) scope for merging here is:
- compiles and no changes for Acts-31 (capybara reports),
- compiles for Acts-32 through Acts-35 (eicweb pipelines).

The next steps are:
- upgrading versions of Acts on eicweb, based on validation in benchmarks.

Out of scope for this PR are:
- issues that may be found later during validation; those will be fixed as they are found, in individual PRs.

This enables the possibility for validation from the actual validation, and hopefully leads to a faster workflow in the long run.

**Comment by wdconinc** [comment]
Two mistakes corrected and force pushed.

Both of the following ifs should apply for Acts_VERSION_MAJOR >= 33, not 32.
- https://github.com/eic/EICrecon/pull/1525/commits/cdcf3d219eb97096a8058441bc593c42369566c3#diff-d7fb27b053533c960f76460cd41ed5af010d6ab2c19aecb233216a29b3a01c2bR96
- https://github.com/eic/EICrecon/pull/1525/commits/cdcf3d219eb97096a8058441bc593c42369566c3#diff-d7fb27b053533c960f76460cd41ed5af010d6ab2c19aecb233216a29b3a01c2bR108

**Comment by wdconinc** [comment]
No major diffs (but many minor diffs): https://wdconinc.github.io/capybara-reports/1c667510d01aed2d228e74ea6e574252/

**Comment by veprbl** [comment]
This doesn't compile against Acts 36.0.0 for me:
```
src/algorithms/tracking/CKFTrackingFunction.cc:62:26: error: 'const eicrecon::CKF' {aka 'const class Acts::CombinatorialKalmanFilter<Acts::Propagator<Acts::EigenStepper<>, Acts::Navigator>, Acts::VectorMultiTrajectory>'} has no member named 'findTracks'
   62 |       return trackFinder.findTracks(initialParameters, options, tracks);
      |                          ^~~~~~~~~~
```
or
```
src/algorithms/tracking/CKFTracking.cc:195:38: error: no matching function for call to 'Acts::PropagatorPlainOptions::PropagatorPlainOptions()'
  195 |         Acts::PropagatorPlainOptions pOptions;
      |                                      ^~~~~~~~
```
and others

**Comment by wdconinc** [comment]
Acts v36 was only released today, see "so additional refactors may hit the Acts main branch that would need porting". Please consider this for up to v35 only.

**Comment by veprbl** [comment]
I'm getting a regression whenever I try to use this with Acts 33 or newer:
```output
[tracking:CentralTrackVertices] [trace] IVFProp        SurfaceReached aborter | Target stepSize (surface) updated to ( +∞,  +∞, 3.53966e-14,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        Stepping loop done.
[tracking:CentralTrackVertices] [trace] IVFProp        Path aborter limit set to 80819.8 (full helix = 161640, previous limit = 1.79769e+308)
[tracking:CentralTrackVertices] [trace] IVFProp        Entering propagation.
[tracking:CentralTrackVertices] [trace] IVFProp         -> near limit, far limit, distance: -1.79769e+308, 1.79769e+308, 1.28682
[tracking:CentralTrackVertices] [trace] IVFProp        Intersection is WITHIN limit
[tracking:CentralTrackVertices] [trace] IVFProp        SurfaceReached aborter | Target stepSize (surface) updated to ( +∞,  +∞, 1.28682,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        PathLimit aborter | Target stepSize (path limit) updated to ( +∞,  +∞, 1.28682,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        Starting stepping loop.
[tracking:CentralTrackVertices] [trace] IVFProp        Step with size = 1.28682 performed
[tracking:CentralTrackVertices] [trace] IVFProp         -> near limit, far limit, distance: -1.79769e+308, 1.79769e+308, -0.000138115
[tracking:CentralTrackVertices] [trace] IVFProp        Intersection is WITHIN limit
[tracking:CentralTrackVertices] [trace] IVFProp        SurfaceReached aborter | Target stepSize (surface) updated to ( +∞,  +∞, -0.000138115,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        PathLimit aborter | Target stepSize (path limit) updated to ( +∞,  +∞, -0.000138115,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        Step with size = -0.000138115 performed
[tracking:CentralTrackVertices] [trace] IVFProp         -> near limit, far limit, distance: -1.79769e+308, 1.79769e+308, 1.48238e-08
[tracking:CentralTrackVertices] [trace] IVFProp        Intersection is WITHIN limit
[tracking:CentralTrackVertices] [trace] IVFProp        SurfaceReached aborter | Target stepSize (surface) updated to ( +∞,  +∞, 1.48238e-08,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        PathLimit aborter | Target stepSize (path limit) updated to ( +∞,  +∞, 1.48238e-08,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        Step with size = 1.48238e-08 performed
[tracking:CentralTrackVertices] [trace] IVFProp         -> near limit, far limit, distance: -1.79769e+308, 1.79769e+308, -1.65217e-12
[tracking:CentralTrackVertices] [trace] IVFProp        Intersection is WITHIN limit
[tracking:CentralTrackVertices] [trace] IVFProp        SurfaceReached aborter | Target stepSize (surface) updated to ( +∞,  +∞, -1.65217e-12,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        PathLimit aborter | Target stepSize (path limit) updated to ( +∞,  +∞, -1.65217e-12,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        Step with size = -1.65217e-12 performed
[tracking:CentralTrackVertices] [trace] IVFProp        SurfaceReached aborter | Target surface reached at distance (tolerance) 0 (1e-12)
[tracking:CentralTrackVertices] [trace] IVFProp         -> near limit, far limit, distance: -1.79769e+308, 1.79769e+308, 0
[tracking:CentralTrackVertices] [trace] IVFProp        Intersection is WITHIN limit
[tracking:CentralTrackVertices] [trace] IVFProp        SurfaceReached aborter | Target stepSize (surface) updated to ( +∞,  +∞,     0,  +∞)
[tracking:CentralTrackVertices] [trace] IVFProp        Stepping loop done.
double free or corruption (!prev)
Command terminated by signal 6
```
Have you tried full event reconstruction?

**Comment by wdconinc** [comment]
> no event-for-event validation has been performed

Intentionally not. We have to get something to compile first and in a container before we can even start the validation in a way that doesn't require everyone to build their own stack.

Making this work event-for-event with acts > 31 is distinctly out of scope.

**Review by veprbl — APPROVED** [review]
This compiles for me.

**Pull request merged**
