### PR TITLE
linux-eic-shell.yml: fix llvm-cov for PRs from fork

### PR DESCRIPTION
**Pull request by veprbl**
Fixes an issue reported in https://github.com/eic/EICrecon/pull/751#issuecomment-1627448876

### CODE REVIEW

**Review by wdconinc — APPROVED** [review]
Looks good. Possibly also an opportunity to highlight as job summary instead of simple echo to log, https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/.

**Comment by veprbl** [comment]
This is an interesting feature. Would be nice to be able to convert html reports to markdown.

**Comment by wdconinc** [comment]
Isn't html a subset of gfmd?

**Comment by veprbl** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<HTML>
  <HEAD>
    <TITLE>The document title</TITLE>
  </HEAD>
  <BODY>
    <H1>Main heading</H1>
    <P>A paragraph.</P>
    <P>Another paragraph.</P>
    <UL>
      <LI>A list item.</LI>
      <LI>Another list item.</LI>
    </UL>
  </BODY>
</HTML>

**Comment by wdconinc** [comment]
https://github.github.com/gfm/#raw-html

**Comment by veprbl** [comment]
Close enough. Though, the links will be dead, since there is no place to host other pages.

**Comment by wdconinc** [comment]
Oh what I would give for gh-pages deployments from pull requests...

**Comment by veprbl** [comment]
You can commit to a repo, so something is possible, but it's not as straightforward as publishing artifact.

**Comment by wdconinc** [comment]
The most promising approach I see currently is to setup a staging environment in a namespace separate from the public deployment environment, where we can then publish under e.g. `pull/id/` or so. Ref https://github.com/actions/deploy-pages

Having this work would make pr reviews of all these gh-pages repos so much easier too.

**Comment by wdconinc** [comment]
We've gotten off topic on this PR though ;-)

**Pull request merged**
