### PR TITLE
feat: add factory for `PhotoMultiplierHitDigi` algorithm and use with dRICH

### PR DESCRIPTION
**Pull request by c-dilks**
### Briefly, what does this PR introduce?
- add factory `PhotoMultiplierHitDigi_factory` to use `PhotoMultiplierHitDigi` algorithm
- fix a few bugs in `PhotoMultiplierHitDigi` algorithm, after testing the factory with the dRICH
- move plugin `src/detectors/RICH` to `src/detectors/DRICH`, and add `PhotoMultiplierHitDigi_factory` to its factory DAG
- move factory `ParticleID_factory_IrtHypothesis` to `src/global/pid`, and rename as `IrtParticleID_factory`

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #327)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no

### Does this PR change default behavior?
no

### CODE REVIEW

**Comment by c-dilks** [comment]
Probably have to wait a few hours for the new `eic-shell` image before CI checks will pass (`epic_Solenoid` issue)

**Comment by c-dilks** [comment]
CI checks pass

**Review by DraTeots — APPROVED** [review]
There are couple of comments but they are rather suggested future TODO but not blockers

**Comment by c-dilks** [comment]
Thanks @DraTeots for the feedback! I will take these suggestions into consideration now that I'm finally ready to start writing `IrtParticleID_factory`.

**Pull request merged**
