### PR TITLE
Adapt ElectronReconstruction to use MatchClusters

### PR DESCRIPTION
**Pull request by tlprotzman**
### Briefly, what does this PR introduce?
The ReconstructedElectron algorithm now uses the particle-cluster associations created by MatchClusters_factory rather than doing it itself.  It makes the collection ReconstructedElectrons a subset collection of ReconstructedParticles, so the association is kept between them.  

I will leave this as a draft until #1277 is merged, then update that code as well to take advantage of it.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #1320 )
- [ ] New feature (issue #__ )
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
ReconstructedElectrons is now a subset collection, but I don't believe that should break anything.

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by tlprotzman** [comment]
Hi @simonge, @wdconinc, while I was working on this it occurred to me that the output of the scattered electron algorithms should be a subset collection of the `ReconstructedElectronsForDIS` collection as well.  Before I do that, I wanted to check that it makes sense to you as well?  A subset of a subset would maintain the relation all the way up to the `ReconstructedParticles` collection, right?

**Comment by simonge** [comment]
> > A subset of a subset would maintain the relation all the way up to the ReconstructedParticles collection, right?
> 
> I haven't used a subset of a subset, but these are really just reference-storing containers, so expected behavior should just store a reference to the original object. If it doesn't, I think podio devs would probably agree that that is a bug and fix it there. @veprbl have you done this?

I believe I've done this before and the behaviour was as expected, it just refers to the collection that owns the objects. It would be easy enough to test again.

**Comment by veprbl** [comment]
I'm uploading capybara report of this for posterity
https://veprbl.github.io/capybara-reports/1fe13e24b65152347eca5828ffcffd80/#ReconstructedElectrons

There is a very minor efficiency loss, and it shows some electrons have charge +1.

**Review by veprbl — APPROVED** [review]
Looks good, and addresses the issue.

**Pull request merged**
