### PR TITLE
add raw tracker hits to output collection

### PR DESCRIPTION
**Pull request by ShujieL**
### Briefly, what does this PR introduce?
I updated the Si raw hits name. Also added all tracker raw hits (Si, MPGD, TOF, B0) to the default podio output collection.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x ] Changes have been communicated to collaborators @mdiefent 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
N/A. Some raw hits name changed. but since it's never used anywhere other than the digitization it should not be an issue.
### Does this PR change default behavior?
N/A

### CODE REVIEW

**Comment by bschmookler** [comment]
I'm missing something here. If we want to add these collections so that we can use the edm4eic::MCRecoTrackerHitAssociation association, don't we also need to write out the sim hits in the EICrecon output?

**Comment by ShujieL** [comment]
> I'm missing something here. If we want to add these collections so that we can use the edm4eic::MCRecoTrackerHitAssociation association, don't we also need to write out the sim hits in the EICrecon output?

You are right. I now added the sim hits as well. Please check.

**Comment by ShujieL** [comment]
> Since capybara doesn't plot diffs when the branch is only present in one of the trees that are being compared (cc @veprbl maybe it should plot anyway then?), can you post a screenshot that shows that the sim and raw hits are being filled?


I downloaded the artifact "rec_dis_18x275_minQ2=1000_craterlake.edm4eic.root"  and printed out the first entry of all raw and sim hits below. All seem good except I can not find "MPGDDIRC" related hits. I don't think that is part of the craterlake detector configuration. 

List of sim hits collections: 
["B0TrackerHits",
"TOFBarrelHits",
"TOFEndcapHits",
"MPGDBarrelHits",
"MPGDDIRCHits",
"OuterMPGDBarrelHits",
"BackwardMPGDEndcapHits",
"ForwardMPGDEndcapHits",
"SiBarrelHits",
"VertexBarrelHits",
"TrackerEndcapHits",
          ]

--------- B0TrackerHits --------------
   entry  subentry                cellID      EDep       time  pathLength  \
0      0         0  18285740503012020630  0.000095  19.944523    0.300014   

   quality  position.x  position.y   position.z  momentum.x  momentum.y  \
0        0 -200.848265  -11.684211  5898.495949   -2.952376   -0.168483   

   momentum.z  
0   85.946098  


--------- _B0TrackerHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     16    2714477136


--------- TOFBarrelHits --------------
   entry  subentry            cellID      EDep      time  pathLength  quality  \
0      0         0  8444726059516252  0.000079  2.268189    0.320931        0   

   position.x  position.y  position.z  momentum.x  momentum.y  momentum.z  
0  567.672047  293.804307    7.405145   28.926764   14.786408     2.29588  


--------- _TOFBarrelHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     17    2714477136


--------- TOFEndcapHits --------------
   entry  subentry                cellID      EDep      time  pathLength  \
0      0         0  18446461982562320762  0.000102  6.521417    0.300573   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0  -79.369954   86.362918     1870.15   -0.109407    0.112651   

   momentum.z  
0    2.542648  


--------- _TOFEndcapHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     23    2714477136


--------- MPGDBarrelHits --------------
   entry  subentry             cellID          EDep      time  pathLength  \
0      0         0  20547724856308029  8.444253e-07  1.847924    3.007889   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0  454.630272  235.878406   -1.571816   28.897316   14.844823   

   momentum.z  
0    2.296773  


--------- _MPGDBarrelHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     17    2714477136


--------- OuterMPGDBarrelHits --------------
   entry  subentry                cellID          EDep      time  pathLength  \
0      0         0  18336898743237886016  4.625650e-07  2.570503    3.011672   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0  647.005713  334.283232   13.700976   28.947805   14.744563   

   momentum.z  
0    2.296384  


--------- _OuterMPGDBarrelHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     17    2714477136


--------- OuterMPGDBarrelHits --------------
   entry  subentry                cellID          EDep      time  pathLength  \
0      0         0  18336898743237886016  4.625650e-07  2.570503    3.011672   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0  647.005713  334.283232   13.700976   28.947805   14.744563   

   momentum.z  
0    2.296384  


--------- _OuterMPGDBarrelHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     17    2714477136


--------- BackwardMPGDEndcapHits --------------
   entry  subentry                cellID      EDep      time  pathLength  \
0      4         0  18415781791911725384  0.000001  4.878497    3.830003   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0 -134.005497 -167.934091   -1105.495   -0.005333    0.002897   

   momentum.z  
0   -0.007661  


--------- _BackwardMPGDEndcapHits_MCParticle --------------
   entry  subentry  index  collectionID
0      4         0    287    2714477136


--------- ForwardMPGDEndcapHits --------------
   entry  subentry                cellID          EDep     time  pathLength  \
0      0         0  18337250324949046610  1.164883e-07  5.23969    3.004258   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0  -72.463651  -39.280252    1485.495   -0.551595   -0.275374   

   momentum.z  
0   11.567967  


--------- _ForwardMPGDEndcapHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     24    2714477136


--------- SiBarrelHits --------------
   entry  subentry             cellID      EDep      time  pathLength  \
0      0         0  16428073830334779  0.000009  1.034982      0.0401   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0  239.919346  125.051853  -18.657885   28.841293   14.957014   

   momentum.z  
0    2.297929  


--------- _SiBarrelHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     17    2714477136


--------- VertexBarrelHits --------------
   entry  subentry              cellID      EDep      time  pathLength  \
0      0         0  495958977700475167  0.000011  0.250645    0.040101   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0   31.900553   16.687056  -35.246282   28.785877   15.063687   

   momentum.z  
0     2.29718  


--------- _VertexBarrelHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     17    2714477136


--------- TrackerEndcapHits --------------
   entry  subentry                cellID      EDep    time  pathLength  \
0      0         0  17292415670977323341  0.000008  1.1087    0.040748   

   quality  position.x  position.y  position.z  momentum.x  momentum.y  \
0        0  -37.632423  -41.402831     249.865   -0.409456   -0.427384   

   momentum.z  
0    3.046554  


--------- _TrackerEndcapHits_MCParticle --------------
   entry  subentry  index  collectionID
0      0         0     12    2714477136


----------------------------------------------------


List of raw hits collections:

[
'B0TrackerRawHits',
'TOFEndcapRawHits',
"TOFBarrelRawHit",
 'BackwardMPGDEndcapRawHits',
 'ForwardMPGDEndcapRawHits',
 'MPGDBarrelRawHits',
 'MPGDDIRCRawHits',
 'OuterMPGDBarrelRawHits',
 'SiBarrelRawHits',
 'SiBarrelVertexRawHits',
 'SiEndcapTrackerRawHits',
]

--------- B0TrackerRawHits --------------
   entry  subentry                cellID  charge  timeStamp
0      0         0  18379753377161622422     378      26820


--------- TOFEndcapRawHits --------------
   entry  subentry           cellID  charge  timeStamp
0      0         0  563415167795578      91       6599


--------- TOFBarrelRawHit --------------
   entry  subentry                cellID  charge  timeStamp
0      0         0  18409025962990936412     318       6196


--------- BackwardMPGDEndcapRawHits --------------
   entry  subentry                cellID  charge  timeStamp
0      4         0  18347946348294248776       1      -5368


--------- ForwardMPGDEndcapRawHits --------------
   entry  subentry              cellID  charge  timeStamp
0      0         0  115967887973356882       0      21647


--------- MPGDBarrelRawHits --------------
   entry  subentry             cellID  charge  timeStamp
0      0         0  20547724856308029       1        -26


--------- OuterMPGDBarrelRawHits --------------
   entry  subentry                cellID  charge  timeStamp
0      0         0  18336898743237886016       0        695


--------- MPGDDIRCRawHits --------------
Empty DataFrame
Columns: [entry, subentry, cellID, charge, timeStamp]
Index: []


--------- OuterMPGDBarrelRawHits --------------
   entry  subentry                cellID  charge  timeStamp
0      0         0  18336898743237886016       0        695


--------- SiBarrelRawHits --------------
   entry  subentry            cellID  charge  timeStamp
0      0         0  6542081317167420      26      16938


--------- SiBarrelVertexRawHits --------------
   entry  subentry                cellID  charge  timeStamp
0      0         0  16918334735439405599      77      12247


--------- SiEndcapTrackerRawHits --------------
   entry  subentry              cellID  charge  timeStamp
0      0         0  173672916800520783      11       2925

**Comment by wdconinc** [comment]
```
--------- B0TrackerHits --------------
entry subentry cellID EDep time pathLength
0 0 0 18285740503012020630 0.000095 19.944523 0.300014

--------- B0TrackerRawHits --------------
entry subentry cellID charge timeStamp
0 0 0 18379753377161622422 378 26820
```

Why is the cellID different? Are these not the same event?

**Comment by ShujieL** [comment]
> ```
> --------- B0TrackerHits --------------
> entry subentry cellID EDep time pathLength
> 0 0 0 18285740503012020630 0.000095 19.944523 0.300014
> 
> --------- B0TrackerRawHits --------------
> entry subentry cellID charge timeStamp
> 0 0 0 18379753377161622422 378 26820
> ```
> 
> 
>     
>   
> 
> Why is the cellID different? Are these not the same event?

Good point. It seems the hit order changed within one event during the digitization step. e.g. the cell ID of 18285740503012020630 you saw with entry 0 subentry 0 in sim hit becomes subentry 3 in raw hits below:

entry  subentry                cellID  charge  timeStamp
0       0         0  18379753377161622422     378      26820
1       0         1  18408744707057267606     162      22562
2       0         2  18351887307222565270     126      18246
3       0         3  18285740503012020630      95      18444

Here's a quick plot of the position x v.s. y from the sim hits and the rec hits (rec to raw is one to one and perserves the order).
I also printed out the cell ID respectively. Not a beautiful plot but you can see that there are two sim hits missed in rec hits (very likely due to the edep cut). Otherwise the sim and rec/raw hits have the same cell ID. 

image

Once we have the raw to sim hits association filled, we can look at this in more details.

**Review by wdconinc — APPROVED** [review]
Nice addition. I was surprised we didn't have this in the output files yet.

@rahmans1 @T-Britton This might increase output file size slightly.

**Comment by wdconinc** [comment]
> This might increase output file size slightly.

rec_dis_18x275_minQ2=1000_craterlake.edm4eic.root: 27.2 MB -> 28.4 MB

**Pull request merged**
