### PR TITLE
treewide: remove truth-based MergedClusters for all calorimeters except Imaging

### PR DESCRIPTION
**Pull request by veprbl**
According to Chao, the MergedClusters algorithm is intended to do merging of ScFi and AstroPix clusters in Imaging. Other calorimeters need not to rely on this.

### Briefly, what does this PR introduce?

Resolves: #474

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
Yes, removes certain outputs. Users are to migrate to use regular clusters.

### Does this PR change default behavior?
Yes, removes certain outputs

### CODE REVIEW

**Comment by veprbl** [comment]
There are still leftover references in docs[1], I can follow up with fixes to those if this is approved

[1] https://github.com/eic/EICrecon/blob/main/docs/design/gaudi-algorithms.md

**Comment by sly2j** [comment]
There were two cluster-merging algorithms in Juggler. I'm not arguing to keep either, but I think there's some confusion there:

* ClusterMerger applies to all calorimeters to merge back clusters that were improperly reconstructed in parts. This was never really used that heavily. This is the algorithm you seem to be referring to here (https://eicweb.phy.anl.gov/EIC/juggler/-/blob/main/JugFast/src/components/ClusterMerger.cpp)
* TruthEnergyPositionClusterMerger is used to combine imaging clusters with scifi clusters in the imaging ecal. I'm not sure this was ported to EICRecon (never looked into it) https://eicweb.phy.anl.gov/EIC/juggler/-/blob/main/JugFast/src/components/TruthEnergyPositionClusterMerger.cpp

**Comment by wdconinc** [comment]
There was also:
- EnergyPositionClusterMerger: which was also not ported (https://eicweb.phy.anl.gov/EIC/juggler/-/blob/main/JugReco/src/components/EnergyPositionClusterMerger.cpp)

**Comment by veprbl** [comment]
Yes, so I may be still ignorant about which cluster merging the Imaging calo relies on, but the point stands that we now assume that nobody actually uses this algorithm, so it can be safely disabled.

**Review by sly2j — DISMISSED** [review]

**Review by Chao1009 — DISMISSED** [review]

**Review by wdconinc — APPROVED** [review]

**Pull request merged**
