### PR TITLE
feat: enable ccache by default if found, unless ENABLE_CCACHE=OFF

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Local development with repeated compile cycles is greatly improved by ccache compiler caching. This enables ccache use by default if `ccache` is available, unless the user disables it. If a user explicitly passes a specific `ccache` as `CMAKE_CXX_COMPILER_LAUNCHER`, it will use that one, though.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
Yes, will compile with `ccache` if available.

### CODE REVIEW

**Comment by veprbl** [comment]
`echo 'export CXX=ccache' >> ~/.profile`?

**Comment by wdconinc** [comment]
> `echo 'export CXX=ccache' >> ~/.profile?`

Yeah, but I don't want to enable it for ALL my compiles (otherwise it really becomes useless because with spack dev I probably rotate through a few GB of cache every day or two).

This is just a convenience feature (which doesn't even work, https://github.com/eic/EICrecon/actions/runs/5694084760/job/15434537689?pr=815), so comments like this are welcome.

**Comment by veprbl** [comment]
Maybe in combination with https://github.com/direnv/direnv ?

**Comment by wdconinc** [comment]
Mostly addressed by #940.

**Pull request closed without merging**
