### PR TITLE
style: apply pre-commit auto fixes treewide

### PR DESCRIPTION
**Pull request by c-dilks**
### Briefly, what does this PR introduce?
Some recent PRs currently have large `diff`s because there are many pre-commit auto fixes not yet applied to `main`. This PR applies all of the auto fixes now.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [x] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no
### Does this PR change default behavior?
no

### CODE REVIEW

**Comment by wdconinc** [comment]
I don't disagree with this but it will not make it easier to do a git blame. The idea behind tacking this onto PRs and not doing this treewide is that it at least hits a commit that was relevant in a git blame.

**Comment by veprbl** [comment]
git blame is not a thing for removed lines.

**Review by veprbl — APPROVED** [review]
For the robots

**Comment by wdconinc** [comment]
> git blame is not a thing for removed lines.

Haha, you're right! I thought this was a PR on the epic repo where the pre-commit has a few formatters.

**Pull request merged**
