### PR TITLE
fix: move remaining JChainFactory algorithms to JChainMultifactory

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
We still had a number of algorithms inheriting JChainFactory, not JChainMultifactory. This migrates these remaining ones to JChainMultifactory.

### What kind of change does this PR introduce?
- [x] Bug fix (issue: migrate all algorithms to JChainMultifactory)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
Many diffs now, https://github.com/eic/EICrecon/actions/runs/7024406714/job/19113472906?pr=1142, but includes timestamp changes and may be due to rollout of recent geometry changes, in particular https://github.com/eic/epic/commit/0746c079002ae5a82961cdb19028dfd56400f289. (we need checksum comparisons)

**Comment by wdconinc** [comment]
Much better. No more diffs https://github.com/eic/EICrecon/actions/runs/7040539144/job/19162385780#step:11:105.

**Review by ruse-traveler — APPROVED** [review]
🎉 Very nice! 🎉

**Comment by wdconinc** [comment]
- eicmkplugin issue at https://github.com/eic/EICrecon/issues/1163
- iwyu changes addressed in https://github.com/eic/EICrecon/pull/1161/commits/af2c0ceb3666f6f39a4be31d9b6acd095c76429e which I'll either fix today or cherry-pick into a separate PR.

I'll go ahead and merge this.

**Pull request merged**
