### PR TITLE
fix: remove non-POD-ness from OrthogonalTrackSeedingConfig

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
The OrthogonalTrackSeedingConfig is now fully POD, which means that including the configuration does not incur the wrath/weight of all of Acts. The TrackSeeding algorithm now takes care of turning POD configs into the Acts config objects (much like how this is done in the other tracking algorithms, though the orthogonal seeding takes it to a new level of course).

Only necessary headers are now included in the POD config, and the headers in TrackSeeding.h and TrackSeeding.cc were reevaluated as well due to this shuffle. Two future FIXMEs have been added since the older Acts version we use has missing includes that have since been added. Check back when we get to Acts 23.0.0 and 27.2.0.

No output collection changes at all expected due to this PR.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators @ShujieL @osbornjd 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Review by osbornjd — DISMISSED** [review]
Looks like a simple refactor to me, which looks fine as far as I can tell

**Comment by wdconinc** [comment]
@osbornjd Thanks for the review. Had to request another one after fixing a conflict.

**Review by osbornjd — APPROVED** [review]
Merge conflicts don't change my review 😁

**Comment by wdconinc** [comment]
> Merge conflicts don't change my review 😁

Tell github that :-)

**Pull request merged**
