### PR TITLE
 feat: rm JChainMultifactory

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This PR removes the JChainMultifactory, now that no factory is using it anymore.

TODO:
- [x] #1418 
- [x] #1419 

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Review by ruse-traveler — COMMENTED** [review]
Hmmm... I'm not seeing any DRICH Cerenkov PIDs in the diffs...

**Comment by wdconinc** [comment]
Old diffs. Wait for update.

**Comment by wdconinc** [comment]
@ruse-traveler Updated, check again.

**Comment by ruse-traveler** [comment]
> @ruse-traveler Updated, check again.

Nice! Not seeing any diffs!

**Review by ruse-traveler — APPROVED** [review]
🥳

**Pull request merged**
