### PR TITLE
Pdu update normal surface

### PR DESCRIPTION
**Pull request by chchatte92**
### Briefly, what does this PR introduce?
This PR introduce angle between the impinged photon angle and the normal to the sensor surface. This is just a draft pull request to check with @c-dilks  if the changes made are meaningful or not. 

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [X] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [X] Changes have been communicated to collaborators
     I have discussed with @c-dilks  personally

### CODE REVIEW

**Comment by c-dilks** [comment]
Changing target branch to `main`, since `pdu-update` will be deleted; please consider rebasing.

**Comment by wdconinc** [comment]
Should this PR be closed?

**Comment by chchatte92** [comment]
> Should this PR be closed?

yes. I am closing it.

**Comment by chchatte92** [comment]
Can I keep the branch for the time being.

**Comment by wdconinc** [comment]
Yes, that's fine. Mostly this is a matter of having an accurate list of in progress PRs that we are tracking.

**Pull request closed without merging**
