### PR TITLE
Merge geometry/rich/richgeo into geometry/rich

### PR DESCRIPTION
**Pull request by veprbl**
### Briefly, what does this PR introduce?

Remove standalone library that is not an actual JANA2 plugin, but pretends to be one.

Resolves: #483

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No

### Does this PR change default behavior?
No

### CODE REVIEW

**Comment by c-dilks** [comment]
Thanks! Yes, this should be a single plugin.

Let's rename it to `richgeo` so it's not confused with a detector plugin. The README should also be updated (I can take care of these if you prefer).

Do we have to flatten it to one directory? It's not necessary, but I prefer to have a clearer separation between the JANA/EICrecon-dependent code and the JANA/EICrecon-independent code.

**Comment by c-dilks** [comment]
> Let's rename it to `richgeo` so it's not confused with a detector plugin. The README should also be updated (I can take care of these if you prefer).

Done and done.

**Comment by veprbl** [comment]
@c-dilks If you think this is good, please approve

**Comment by c-dilks** [comment]
> I should also test this with https://github.com/eic/EICrecon/pull/393.

I can no longer do this thanks to new upstream issues, so I'll deal with that later after this PR is merged.

**Review by c-dilks — APPROVED** [review]

**Comment by c-dilks** [comment]
(need another reviewer since I pushed to this branch)

**Comment by veprbl** [comment]
> > Do we have to flatten it to one directory?
> 
> Awaiting feedback on this.

You could set sources manually instead of calling `plugin_glob_all`. I just don't see the point. The separation should be already apparent from the filenames.

**Pull request merged**
