### PR TITLE
build: use `EDM4EIC_INCLUDE_DIR` from `find_package`

### PR DESCRIPTION
**Pull request by c-dilks**
### Briefly, what does this PR introduce?
EICrecon should not have to set `EDM4EIC_INCLUDE_DIR`. With https://github.com/eic/EDM4eic/pull/37 this can be done automatically from `find_package(EDM4EIC)`.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no

### Does this PR change default behavior?
no

### CODE REVIEW

**Comment by veprbl** [comment]
Is there a bug that you saw, @c-dilks ?

**Comment by veprbl** [comment]
I think this change was a correct action.

**Comment by veprbl** [comment]
(We'd need to remove instances `${EDM4EIC_INCLUDE_DIR}` too)

**Comment by c-dilks** [comment]
No bug, just trying to clean things up. I thought I needed https://github.com/eic/EDM4eic/pull/37 to do this, but seems not.

I'll re-open this one then, but I'm not sure how to handle `make_datamodel_glue.py`: the build CI check gets stuck here:
https://github.com/eic/EICrecon/blob/860606fbcfdd64ce33cd1de197a3253d8d09e9fb/src/services/io/podio/make_datamodel_glue.py#L56-L65

**Comment by c-dilks** [comment]
These `<package>_INCLUDE_DIR` variables are used in a lot of places... I need help with this PR (and I should be prioritizing PID stuff anyway).

**Comment by c-dilks** [comment]
Closing in favor of https://github.com/eic/EICrecon/pull/720

**Pull request closed without merging**
