### PR TITLE
fix: propagate parameters from reco_flags to cpp plugins

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This addresses a lot of the discrepancies in https://eic.github.io/EICrecon/#/table_flags/flags_view

### What kind of change does this PR introduce?
- [x] Bug fix (issue: reco_flags duplicates parameters)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
Use the pion flags file for diffs to have higher probability that Hcal factories are initialized.

**Review by DraTeots — APPROVED** [review]

**Comment by c-dilks** [comment]
There are still some differences at https://wdconinc.github.io/EICrecon/#/table_flags/flags_view, is this the latest version? Also, I will take care of the DRICH ones in a separate PR.

**Comment by wdconinc** [comment]
I think my main is pointing to a different commit by now.

**Comment by wdconinc** [comment]
Ah, no, my main is pointing to a but the last commit here. The remaining differences in protoclusters is still under investigation. But I think this is still ready for merging.

**Comment by wdconinc** [comment]
There is also the issue that the gh-pages can only show either arches or brycecanyon, and EICrecon only initializes a factory when needed. So part of the chain is just not exercised.

**Comment by c-dilks** [comment]
I believe these are the remaining differences:
```
#
#key                                                           => reco_flags.py         VS native eicrecon
#
BEMC:EcalBarrelImagingRawHits:readoutClass                     => pixel                 VS
BEMC:EcalBarrelScFiRawHits:energyResolutions                   =>                       VS 0
BEMC:EcalBarrelScFiRawHits:readoutClass                        => light_guide           VS
EEMC:EcalEndcapPInsertIslandProtoClusters:dimScaledLocalDistXY => 1.5,1.5               VS 1.8,1.8
EEMC:EcalEndcapPInsertIslandProtoClusters:localDistXY          => 10,10                 VS
EEMC:EcalEndcapPInsertIslandProtoClusters:minClusterCenterEdep => 0.01                  VS 0.03
EEMC:EcalEndcapPInsertIslandProtoClusters:minClusterHitEdep    => 0                     VS 0.001
EEMC:EcalEndcapPInsertRecHits:capacityADC                      => 16384                 VS 8096
EEMC:EcalEndcapPInsertRecHits:dynamicRangeADC                  => 3.0                   VS 0.1
EEMC:EcalEndcapPInsertRecHits:pedestalMean                     => 100                   VS 400
EEMC:EcalEndcapPInsertRecHits:pedestalSigma                    => 0.7                   VS 3.2
EEMC:EcalEndcapPInsertRecHits:samplingFraction                 => 0.03                  VS 0.998
EEMC:EcalEndcapPInsertRecHits:thresholdFactor                  => 5.0                   VS 4
EEMC:EcalEndcapPInsertRecHits:thresholdValue                   => 2                     VS 0
EEMC:EcalEndcapPInsertTruthClusters:enableEtaBounds            => 1                     VS 0
EEMC:EcalEndcapPInsertTruthClusters:logWeightBase              => 6.2                   VS 3.6
EEMC:EcalEndcapPIslandProtoClusters:dimScaledLocalDistXY       => 1.5,1.5               VS 1.8,1.8
EEMC:EcalEndcapPIslandProtoClusters:localDistXY                => 10,10                 VS
EEMC:EcalEndcapPIslandProtoClusters:minClusterCenterEdep       => 0.01                  VS 0.03
EEMC:EcalEndcapPIslandProtoClusters:minClusterHitEdep          => 0                     VS 0.001
HCAL:HcalBarrelIslandProtoClusters:localDistXY                 => 150,150               VS 1.5,1.5
HCAL:HcalEndcapNIslandProtoClusters:localDistXY                => 150,150               VS 1.5,1.5
HCAL:HcalEndcapPInsertIslandProtoClusters:localDistXY          =>                       VS 1.5,1.5
HCAL:HcalEndcapPInsertRecHits:samplingFraction                 => 0.998                 VS 1
HCAL:HcalEndcapPIslandProtoClusters:localDistXY                => 150,150               VS 1.5,1.5
tracking:CentralCKFTrajectories:Chi2CutOff                     => 15                    VS 50
```
New issue+PR or fix them here?

**Review by c-dilks — DISMISSED** [review]

**Comment by wdconinc** [comment]
```
HCAL:HcalBarrelIslandProtoClusters:localDistXY                 => 150,150               VS 1.5,1.5
HCAL:HcalEndcapNIslandProtoClusters:localDistXY                => 150,150               VS 1.5,1.5
HCAL:HcalEndcapPIslandProtoClusters:localDistXY                => 150,150               VS 1.5,1.5
```
That just can't be right. Do we really want localDistXY to be 150 cm?

**Comment by wdconinc** [comment]
Remaining (along with the HCAL localDistXY above) are
```
BEMC:EcalBarrelImagingRawHits:readoutClass                     => pixel                 VS
BEMC:EcalBarrelScFiRawHits:energyResolutions                   =>                       VS 0
BEMC:EcalBarrelScFiRawHits:readoutClass                        => light_guide           VS
tracking:CentralCKFTrajectories:Chi2CutOff                     => 15                    VS 50
```

**Comment by c-dilks** [comment]
Now we are down to:
```
BEMC:EcalBarrelImagingRawHits:readoutClass            => pixel                 VS
BEMC:EcalBarrelScFiRawHits:energyResolutions          =>                       VS 0
BEMC:EcalBarrelScFiRawHits:readoutClass               => light_guide           VS

EEMC:EcalEndcapPInsertIslandProtoClusters:localDistXY => 10,10                 VS 1,1
EEMC:EcalEndcapPIslandProtoClusters:localDistXY       => 10,10                 VS 1,1

HCAL:HcalBarrelIslandProtoClusters:localDistXY        => 150,150               VS 1.5,1.5
HCAL:HcalEndcapNIslandProtoClusters:localDistXY       => 150,150               VS 1.5,1.5
HCAL:HcalEndcapPInsertIslandProtoClusters:localDistXY =>                       VS 1.5,1.5
HCAL:HcalEndcapPIslandProtoClusters:localDistXY       => 150,150               VS 1.5,1.5
```
I suppose `EEMC` and `HCAL` differences are caused by https://github.com/eic/EICrecon/issues/433.

**Comment by wdconinc** [comment]
> Now we are down to:
> ```
>  BEMC:EcalBarrelImagingRawHits:readoutClass            => pixel                 VS
> BEMC:EcalBarrelScFiRawHits:readoutClass               => light_guide           VS
> ```
Afaik this value is unused, and pixel or light_guide are not even classes. As introduced by https://github.com/eic/EICrecon/pull/253/commits/e6f1f93aba923c36939f63581dbe8df9fb04e3ba, @faustus123, does this do something new in EICrecon?

> ```
> BEMC:EcalBarrelScFiRawHits:energyResolutions          =>                       VS 0
> ```
I'd argue this is not right. Every other calorimeter has a non-zero energy resolution term, so this may need to be `{0,0.02,0}` to allow fair comparison with the other barrel calorimeter. @mariakzurek?

> ```
> EEMC:EcalEndcapPInsertIslandProtoClusters:localDistXY => 10,10                 VS 1,1
> EEMC:EcalEndcapPIslandProtoClusters:localDistXY       => 10,10                 VS 1,1
> ```
I'll fix those. I keep thinking in mm, not cm, as the basic unit.

> ```
> HCAL:HcalBarrelIslandProtoClusters:localDistXY        => 150,150               VS 1.5,1.5
> HCAL:HcalEndcapNIslandProtoClusters:localDistXY       => 150,150               VS 1.5,1.5
> HCAL:HcalEndcapPInsertIslandProtoClusters:localDistXY =>                       VS 1.5,1.5
> HCAL:HcalEndcapPIslandProtoClusters:localDistXY       => 150,150               VS 1.5,1.5
> ```
> I suppose `EEMC` and `HCAL` differences are caused by https://github.com/eic/EICrecon/issues/433.
There is even more wrong here than meets the eye. The intention is that only one of the |localDistXY` etc pairs is supposed to be set. If multiple are set, then the last one in the arbitrary list in the algorithm is used, in this case `dimScaledLocalDistXY`, and that one should not have dimensions. So, I'm going to punt on fixing Hcal clustering for this PR.

**Comment by wdconinc** [comment]
Juggler didn't have `pixel` either, https://eicweb.phy.anl.gov/EIC/juggler/-/blob/main/JugReco/src/components/ImagingPixelReco.cpp#L45.

**Comment by faustus123** [comment]
> Afaik this value is unused, and pixel or light_guide are not even classes. As introduced by [e6f1f93](https://github.com/eic/EICrecon/commit/e6f1f93aba923c36939f63581dbe8df9fb04e3ba), @faustus123, does this do something new in EICrecon?
> 

I cannot recall where those came from. I just poked around in my old work directories, but am not seeing "pixel" show up in this context. It is a mystery to me. So is this something that should be left as an empty string?

**Comment by wdconinc** [comment]
> So is this something that should be left as an empty string?

Hits refer to CellIDs. The CellID includes bits that define the detector. The detector can have multiple readout collections, but typically has only one. When there are multiple readout collections for a detector, then the readoutClass field is used to choose which readout collection to use. That does not apply here, and I think an empty string should be used.

**Comment by faustus123** [comment]
OK. Since they are already empty strings in the library code, then I take it no action is needed. You just wanted verification that there was not a reason why they should actually be set to "pixel" and "light_guide". Let me know if this is incorrect and you need more from me.

**Comment by mariakzurek** [comment]
> I'd argue this is not right. Every other calorimeter has a non-zero energy resolution term, so this may need to be `{0,0.02,0}` to allow fair comparison with the other barrel calorimeter. @mariakzurek?

This is right only for the Imaging Calorimetr; I guess it has been copied for other calorimeters from the imaging layers. It's 2% flat resolution on single pixel readout for AstroPix. @Chao1009 @sly2j

**Comment by wdconinc** [comment]
Verified with @mariakzurek that `BEMC:EcalBarrelScFiRawHits:energyResolutions` should be `0` as in the cpp file right now, not empty string `''` as in the reco_flags (since that is not actually a specification of a value, just a deferral to the default in the cpp file).

**Comment by wdconinc** [comment]
So, only remaining issue is:
```
HCAL:HcalBarrelIslandProtoClusters:localDistXY        => 150,150               VS 1.5,1.5
HCAL:HcalEndcapNIslandProtoClusters:localDistXY       => 150,150               VS 1.5,1.5
HCAL:HcalEndcapPInsertIslandProtoClusters:localDistXY =>                       VS 1.5,1.5
HCAL:HcalEndcapPIslandProtoClusters:localDistXY       => 150,150               VS 1.5,1.5
```

**Review by DraTeots — APPROVED** [review]

**Pull request merged**
