### PR TITLE
Rearrange the position calls in MatrixTransferStatic algorithm

### PR DESCRIPTION
**Pull request by simonge**
### Briefly, what does this PR introduce?
Hopefully increases the efficiency of the MatrixTransferStatic algorithm by converting 2D->3D coordinates rather than 2D->3D->2D as CellDPositionConverter does. Makes use of the readout passed as config so it doesn't need to look this up every call from the CellID.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [x] Other: Hopefully streamlines the algorithm a bit. Very minor improvement.

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
NA
### Does this PR change default behavior?
NA

### CODE REVIEW

**Comment by wdconinc** [comment]
@simonge Do you want to revive this (fix conflicts) or is this something that can be closed due to other activity?

**Comment by simonge** [comment]
Might as well try and bring it up to date. Hopefully in a few minutes...

**Comment by wdconinc** [comment]
I assume you don't expect any differences due to this change? https://eicrecon.epic-eic.org/pr/1046/capybara/rec_dis_18x275_minQ2=1000_craterlake/index.html#ForwardRomanPotRecParticles: green before, red after.

**Comment by simonge** [comment]
> I assume you don't expect any differences due to this change? https://eicrecon.epic-eic.org/pr/1046/capybara/rec_dis_18x275_minQ2=1000_craterlake/index.html#ForwardRomanPotRecParticles: green before, red after.

I presume there isn't such a report from when this was last up to date?

**Comment by wdconinc** [comment]
Unfortunately not (we don't keep the graphics output, but even the logs are expired, e.g. https://github.com/eic/EICrecon/actions/runs/6409910580/job/17402104851?pr=1046).

**Comment by simonge** [comment]
The problem here is I don't completely understand the translation between segmentation position, detector element position and global position. As it is, this tried to go straight from segmentation to global, which appears to be wrong. By the time it works as expected the code is less clear and any efficiency increase is negligible. 

Functions could be added to dd4hep to more easily access the intermediate translation steps without doing them twice but it's not worth dwelling on as this method is hopefully being superseded.

**Pull request closed without merging**
