### PR TITLE
labeler.yml: fix config for v5

### PR DESCRIPTION
**Pull request by veprbl**
Fixes a regression from #1258

### CODE REVIEW

**Comment by veprbl** [comment]
@wdconinc My understanding, is that we can't (easily?) test until this is merged.

**Comment by wdconinc** [comment]
Yes, pull_request_target always uses what's in main.

**Comment by wdconinc** [comment]
If you wanted to, you could submit from the default branch of a fork. But I think this one is just hard to test in any case.

**Comment by veprbl** [comment]
Passes syntax check in https://github.com/veprbl/EICrecon/pull/12

**Review by wdconinc — APPROVED** [review]
Looks right to me after reading how the condig was changed. Sorry for the regression.

**Pull request merged**
