### PR TITLE
feat: PFRICH digitization plugin

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This PR introduces PFRICH digitization based on the DRICH digitization. No thought went into the parameters; just setting up the plugin for someone to change the numbers :-)

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue: PFRICH digitization)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators @billlee77 @kkauder 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
Yes, will expected PFRICH input collections, which are available as of https://github.com/eic/epic/pull/664.

### CODE REVIEW

**Review by veprbl — APPROVED** [review]
Diff LGTM

**Comment by kkauder** [comment]
Sorry for being late. No issue with the merge, but when you have a chance, @alexander-kiselev , please take a look at the numbers, e.g. https://github.com/eic/EICrecon/pull/1354/files#diff-1533cd7a6e6f90702dfb3f3bc64382cf88107b73da63eca441c774c28ace755fR28-R58

**Comment by alexander-kiselev** [comment]
Hello colleagues,

  I apologize for returning back late to you concerning this topic. Where from do these numbers come? Essentially none of the ones where I can guess on their meaning / units is correct. Actually, what other detectors use this digitization template?

  Cheers,
    Alexander.

________________________________

**Comment by wdconinc** [comment]
@alexander-kiselev Please correct them.

**Comment by wdconinc** [comment]
> If there are any numbers that need to change, please open a new issue for them.

And this still applies!

**Pull request merged**
