### PR TITLE
fix: split island clusters with >1 maxima

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This adds the part of the island clustering algorithm that splits clusters with multiple maxima.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (more like old feature)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators: @Chao1009 @veprbl 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No (default splitting is off).

### CODE REVIEW

**Comment by wdconinc** [comment]
Can't add @Chao1009 as reviewer.

**Comment by veprbl** [comment]
```
In file included from /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterIslandCluster.cc:7:
/home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterIslandCluster.h:292:14: error: no member named 'verbose' in 'spdlog::logger'
      m_log->verbose("Multiple ({}) maxima found, added a ProtoClusters for each maximum", maxima.size());
      ~~~~~~~^
4 errors generated.
```

**Comment by wdconinc** [comment]
Aware of the issues and fixing them now. Will be straightforward.

**Comment by wdconinc** [comment]
Protoclusters splitting can result in protoclusters without hits after all (secondary maximum but too low weight). That needed to be handled in the CoG clusters.

In juggler collections this was just an empty collection. In EICrecon it leads to a nullptr in a vector (which then needs checking). Another class of bugs... Probably not just here.

**Comment by wdconinc** [comment]
Runs without error. Needs verification with ROOT on artifacts tomorrow...

**Comment by wdconinc** [comment]
But ready for review

**Comment by wdconinc** [comment]
## Before (main)

Multi-cluster events in 10x100 minQ2 1000, brycecanyon:
image

Specific event with **one** cluster:
```
root [7] events->Scan("EcalEndcapNClusters.energy:EcalEndcapNClusters.nhits:EcalEndcapNClusters.position.x:EcalEndcapNClusters.position.y:@EcalEndcapNClusters#1.size()","Entry$==72")
***********************************************************************************
*    Row   * Instance * EcalEndca * EcalEndca * EcalEndca * EcalEndca * @EcalEndc *
***********************************************************************************
*       72 *        0 * 4.9170603 *        23 * -139.4617 * 482.18844 *         0 *
***********************************************************************************
==> 1 selected entry
(long long) 1
```

## After (here)

Multi-cluster events in 10x100 minQ2 1000, brycecanyon:
image

Specific event with **two** clusters:
```
root [17] events->Scan("EcalEndcapNClusters.energy:EcalEndcapNClusters.nhits:EcalEndcapNClusters.position.x:EcalEndcapNClusters.position.y:@EcalEndcapNClusters#1.size()","Entry$==72")
***********************************************************************************
*    Row   * Instance * EcalEndca * EcalEndca * EcalEndca * EcalEndca * @EcalEndc *
***********************************************************************************
*       72 *        0 * 2.0209455 *        23 * -134.3986 * 452.98172 *         0 *
*       72 *        1 * 2.8961153 *        23 * -144.2483 * 510.61731 *         0 *
***********************************************************************************
==> 2 selected entries
(long long) 2
```

## Comments
The total number of hits before splitting is indicated as `nhits` for both split clusters. Because EICrecon does not support relations, the number of hits in the relations table is zero and cannot be used to get the actual number of hits. This is probably an actual bug in the algorithm, and needs fixing.

**Comment by wdconinc** [comment]
I think this looks like it's working (i.e. doing something that is consistent with splitting clusters). The next step is probably up to detector experts who can decide whether to split or not for their detector, and with what parameters. I think ready for review and merging.

**Comment by Chao1009** [comment]
Thank you for porting it. It looks reasonable.

**Comment by wdconinc** [comment]
@Chao1009 can you click approve?

**Review by Chao1009 — APPROVED** [review]

**Pull request merged**
