### PR TITLE
Fixes for Dmitry R.'s platform

### PR DESCRIPTION
**Pull request by nathanwbrei**
### Briefly, what does this PR introduce?
@DraTeots helped me quite a bit with PR #578. He made a lot of small fixes in order to get EICrecon to build on his system. For the sake of keeping the huge PR as manageable as possible, I didn't include these in the final PR. Rather than throw this work away, however, I cherry-picked the changes that *didn't* make it into main so that we can have a look at them and decide what to keep. 

Probably the most important fix in here is an issue with Eigen alignments. 

The changes related to exception handling are going to inform my response to issue #625. 

### What kind of change does this PR introduce?
- [x] Bug fix (issue #__)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### CODE REVIEW

**Comment by veprbl** [comment]
Can we review these changes in separate PRs? Some are not uncontroversial.

**Comment by nathanwbrei** [comment]
> Can we review these changes in separate PRs? Some are not uncontroversial.

Absolutely! I fully expect this us to cherry pick and/or drop some of these commits. The important thing is that we all see what the changes are, and more or less agree on which should make it into master. 

When it comes to specifics:

* Some of the changes relating to Eigen alignment look uncontroversial to me (e.g. the missing pragma once's). Although I'm pretty sure there was also some code that got commented out in there, and I don't know if that code was important.

* Removing the redundant `ParticlesWithAssociation` class (and some of the many many unused headers) seems like a good idea because it would reduce code entropy and might even improve compilation times slightly.

* The exception handling changes definitely need to be their own PR, and I am experimenting with doing it a little bit differently than what is here. 

* I have no idea what the changes to the CMake project structure entail or why we might want them. Are these the changes that you flagged as being possibly controversial?

**Comment by wdconinc** [comment]
@nathanwbrei @veprbl @DraTeots Can this be closed?

**Comment by veprbl** [comment]
I didn't see useful changes that weren't yet ported.

**Pull request closed without merging**
