### PR TITLE
feat!: remove reco_flags.py, defer to factory parameters

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This removes the reco_flags python front-end. Any parameter changes have to be applied in the c++ factories. This removes duplication of default values and interfaces, along with a potential for mistakes and inconsistencies.

### What kind of change does this PR introduce?
- [x] Bug fix (issue: a whole bunch)
- [x] New feature (issue: remove reco_flags)
- [x] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [x] Tests for the changes have been updated
  - [x] TODO: update CI tests
- [x] Documentation has been added / updated
  - [x] TODO: update documentation 
- [x] Changes have been communicated to collaborators, @faustus123 @DraTeots 

### Does this PR introduce breaking changes? What changes might users need to make to their code?
Yes. Use `eicrecon` instead of `run-eicrecon...`

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
@c-dilks Added you as reviewer since you were the last one to touch the reco_flags.py script in https://github.com/eic/EICrecon/pull/442. Let me know if that introduced any need for more propagation to factories, but I don't think so.

**Review by faustus123 — COMMENTED** [review]
This looks good to pull it out of the CI workflow.

The one question I have is whether the website is really obsolete. It looked like it could be useful as a web-enabled browser of config. parameters with minimal work. I don't know though and @DraTeots would need to comment. Otherwise, I do not have an issue with the PR.

**Comment by wdconinc** [comment]
> whether the website is really obsolete

I was torn about this (in part because I don't want to throw out good work by a promising student). Maybe it just needs significant edits, removing the columns and diffs, because those are by definition going to be irrelevant or false positives in a CI job.

**Comment by c-dilks** [comment]
> @c-dilks Added you as reviewer since you were the last one to touch the reco_flags.py script in #442. Let me know if that introduced any need for more propagation to factories, but I don't think so.

Fine with me, all dRICH params are now set in C++.

**Comment by DraTeots** [comment]
It was created to be thrown =) We'll fix the page, lets commit it

**Review by faustus123 — APPROVED** [review]

**Pull request merged**
