### PR TITLE
add B0TRK to reco sequence

### PR DESCRIPTION
**Pull request by michael-pitt**
### Briefly, what does this PR introduce?

Adding reconstruction of track hits in B0 detector

### What kind of change does this PR introduce?
- [ X] Bug fix (B0TRK declared but not linked in cmake file)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR change default behavior?
Should not

### CODE REVIEW

**Comment by wdconinc** [comment]
See also https://github.com/eic/EICrecon/pull/405. @rahmans1 @michael-pitt please make sure you coordinate.

**Comment by michael-pitt** [comment]
Hi @wdconinc, indeed, @rahmans1 drew my attention yesterday that this addition was already included in his PR, which incorporates a new tracking algorithm.  If you agree, I will cancel this PR (unless it will take time until #405 is merged)

**Comment by wdconinc** [comment]
> If you agree, I will cancel this PR (unless it will take time until #405 is merged)

I don't know what the timeline of #405 is. @rahmans1 ?

**Review by DraTeots — APPROVED** [review]

**Comment by DraTeots** [comment]
From the code introduced in this PR point of view everything is fine. Should we merge it despite B0 isn't fully working or not?

**Comment by michael-pitt** [comment]
Hi @DraTeots 
This PR includes the B0 tracker, and one can have B0 tracker RecoHits in the output. The #405 deals with reconstructing tracks from the RecoHits, which is next steps in the reconstruction chain, so maybe for now we can include the first step, and once the tracks are available they can be included as well.

**Pull request merged**
