### PR TITLE
fix: allow for reordered DD4hep_service geometry arguments

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This fixes the DD4hep_service to allow querying the geometry in any order, and avoids race conditions in the `detector()` and `cellIDPositionConverter()` calls.

TODO:
- [x] revert 167ae084f932502799ace697ccf0c9d30e1a5308

### What kind of change does this PR introduce?
- [x] Bug fix (issue #1032)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
Hopefully one of the CI jobs will fail. Then I'll merge the fix, and then hopefully CI will not fail anymore.

**Comment by wdconinc** [comment]
> Hopefully one of the CI jobs will fail.

Seems like it's not going to fail since it requires on specific ordering and only calling specific algorithms.

**Comment by wdconinc** [comment]
@simonge This change should fix it. I tested with
```
eicrecon -Ppodio:output_file=rec_dis_18x275_minQ2=1000_brycecanyon.edm4eic.root -Ppodio:output_include_collections=ForwardOffMRecParticles sim_dis_18x275_minQ2=1000_brycecanyon.edm4hep.root
```
and had no more failures.

**Comment by simonge** [comment]
Thanks @wdconinc, trying to test this but today a bug loading the geometry xml has appeared.

**Review by simonge — APPROVED** [review]
Works well, thanks

**Comment by wdconinc** [comment]
Reverted the reordering that was intended to trigger the bug. Needs new approval.

**Review by veprbl — APPROVED** [review]

**Pull request merged**
