### PR TITLE
fix: use jacobian to convert bound covariance to free 3d position error

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This uses the target surface jacobian to convert the covariance in bound coordinates to the free covariance that can be used to obtain the local position error on the projected point on the target surface.

### What kind of change does this PR introduce?
- [x] Bug fix (issue: positionError is not filled by TrackProjector algorithm)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
This appears to make sense, e.g. when plotting `surface, position.{x, y, z}, positionError.{xx, yy, zz, xy, xz, yz}`
```
root [23] events->Scan("_CentralTrackSegments_points.surface:_CentralTrackSegments_points.position.x:_CentralTrackSegments_points.position.y:_CentralTrackSegments_points.position.z:_CentralTrackSegments_points.positionError.xx:_CentralTrackSegments_points.positionError.yy:_CentralTrackSegments_points.positionError.zz:_CentralTrackSegments_points.positionError.xy:_CentralTrackSegments_points.positionError.xz:_CentralTrackSegments_points.positionError.yz","","precision=4 col=24lx:")
**************************************************************************************************************************************************************
*    Row   * Instance * _CentralTrackSegments_po * _CentralT * _CentralT * _CentralT * _CentralT * _CentralT * _CentralT * _CentralT * _CentralT * _CentralT *
*    Row   * Instance *                  surface *         x *         y *         z *        xx *        yy *        zz *        xy *        xz *        yz *
**************************************************************************************************************************************************************
*        0 *        0 *         2400004000002000 *      -317 *    -149.1 *     999.9 * 0.0001226 * 0.0003714 * 2.024e-36 * -0.000148 * -1.41e-20 * 2.577e-20 *
*        0 *        1 *         2400002000002000 *    -225.2 *    -106.3 *     699.9 * 0.0002649 * 0.0009201 * 5.019e-36 * -0.000396 *  -3.4e-20 * 6.553e-20 *
*        0 *        2 *         2100002000002000 *    -148.8 *    -70.55 *     449.9 *  0.002174 *   0.00914 * 5.002e-35 * -0.004282 * -3.25e-19 * 6.719e-19 *
*        0 *        3 *         1e00002000001f00 *    -87.73 *    -41.67 *     249.9 *   0.01037 *   0.04538 *  2.48e-34 *  -0.02148 * -1.59e-18 *  3.35e-18 *
*        0 *        4 *         1c00004000006500 *    -43.32 *    -20.67 *     104.5 *   0.01608 *   0.07189 *   0.09423 *    -0.034 * 0.0006693 * -0.001415 *
*        0 *        5 *         1c00002000006500 *    -32.23 *    -16.06 *     72.04 *    0.7777 *     3.477 *     14.78 *    -1.644 *    0.1134 *   -0.2398 *
*        0 *        6 *          200002000000000 *    -25.29 *     -12.6 *     48.38 *    0.5964 *     2.403 *     9.473 *    -1.197 *  -0.00127 *  0.002548 *
*        0 *        7 *         2600002000002c00 *    -443.9 *    -228.3 *      1485 * 0.0001325 * 0.0003453 * 2.045e-36 * -0.000155 * -1.50e-20 * 2.501e-20 *
*        0 *        8 *         2600002010000000 *    -442.3 *    -227.5 *      1480 * 0.0001296 * 0.0003377 *         0 * -0.000152 *         0 *         0 *
*        0 *        9 *         2400004000002000 *      -303 *    -154.3 *     999.9 * 0.0001367 * 0.0003632 * 2.125e-36 * -0.000160 * -1.55e-20 * 2.612e-20 *
*        0 *       10 *         2400002000002000 *    -215.7 *    -109.1 *     699.9 *  0.000297 *  0.000909 * 5.278e-36 * -0.000425 * -3.72e-20 * 6.682e-20 *
*        0 *       11 *         2100002000002000 *    -142.8 *    -71.72 *     449.9 *  0.002346 *  0.008704 * 5.016e-35 *  -0.00435 * -3.38e-19 * 6.565e-19 *
*        0 *       12 *         1e00002000001f00 *    -84.39 *     -42.1 *     249.9 *  0.009544 *     0.038 * 2.157e-34 *  -0.01887 * -1.43e-18 * 2.859e-18 *
*        0 *       13 *         1c00004000006500 *       -43 *    -21.35 *     108.5 *   0.01607 *   0.07185 *    0.1137 *  -0.03398 *  0.001693 * -0.003581 *
*        0 *       14 *         1c00002000006500 *    -32.51 *    -15.46 *     68.87 *     0.777 *     3.474 *     13.39 *    -1.643 *   0.01019 *  -0.02155 *
*        0 *       15 *          200002000000000 *    -25.51 *    -12.14 *     45.91 *    0.5537 *     2.446 *     8.632 *    -1.164 * -0.000865 *  0.001818 *
*        0 *       16 *         2800002000003e00 *    -274.5 *    -245.6 *      1850 *   0.07739 *    0.0771 *         0 *  0.000685 *         0 *         0 *
*        0 *       17 *         2600004000002e00 *    -238.6 *    -217.6 *      1615 *     9.551 *     15.09 *  1.34e-31 *    -11.98 * -1.13e-15 *  1.42e-15 *
*        0 *       18 *         2600002000002e00 *    -218.5 *      -202 *      1485 *     6.726 *     10.18 * 9.332e-32 *    -8.272 * -7.92e-16 * 9.744e-16 *
*        0 *       19 *         2600002010000000 *    -217.7 *    -201.3 *      1480 *     6.619 *     9.999 *         0 *    -8.133 *         0 *         0 *
*        0 *       20 *         2400006000002000 *    -197.7 *    -185.5 *      1350 *     4.392 *     6.339 *   6.1e-32 *    -5.275 * -5.17e-16 * 6.218e-16 *
*        0 *       21 *         2400004000002000 *    -144.8 *    -142.1 *     999.9 *    0.9338 *     1.183 * 1.243e-32 *     -1.05 * -1.07e-16 * 1.212e-16 *
*        0 *       22 *         2400002000002200 *    -100.7 *    -103.2 *     699.9 *   0.08063 *   0.09074 * 1.017e-33 *  -0.08531 * -9.05e-18 *  9.59e-18 *
*        0 *       23 *         2100002000002200 *    -65.06 *    -69.51 *     449.9 *    0.3754 *    0.3413 * 4.514e-33 *    -0.337 * -4.11e-17 * 3.758e-17 *
*        0 *       24 *         1e00002000002100 *    -37.52 *    -41.56 *     249.9 *     9.019 *      8.95 *  8.22e-32 *  -0.02575 * -8.46e-16 * 1.589e-16 *
```
Interpretation:
- multiple surface IDs shown as long unsigned hex in 3rd column,
- if some surface ID has fixed positions in z, e.g. 0x2600002010000000 at z = 1480mm -> cross-correlations with that dimension are always zero, but cross-correlations in xy are non-zero.

**Comment by wdconinc** [comment]
@mposik1983 Not sure how you did the track projection covariance study that was shown at the collaboration meeting, but this might be useful.

**Comment by mposik1983** [comment]
@wdconinc Nice. For the study I showed at the collaboration meeting I was using directionerror: https://github.com/eic/EICrecon/blob/main/src/algorithms/tracking/TrackProjector.cc#L133C1-L133C84

**Comment by wdconinc** [comment]
I wonder if we need to use the free directionError too... might be useful to compare differences.

**Comment by wdconinc** [comment]
Checked that `directionError` is appropriately using bound parameters.

What's less clear is whether `momentum` and `momentumError` are correct. EDM4eic implies these are cartesian components, not q/p, theta, phi as is done here. In that case, we do need the conversion to free. @jdbrice or @tylerkutz are you using `momentum` and/or `momentumError` from these TrackPoints? Would it break your workflows or can we just change this to conform?

**Comment by wdconinc** [comment]
Within the scope of this PR (positionError), this is ready for review and merging. I'll file an issue for the momentum and momentumError so we can keep track of it.

**Review by ShujieL — APPROVED** [review]

**Pull request merged**
