### PR TITLE
feat(DRICH)!: enable raw hits and projected tracks by default

### PR DESCRIPTION
**Pull request by c-dilks**
### Briefly, what does this PR introduce?
The dRICH IRT-PID implementation has not been approved in time for production 23.5. In order to at least have _something_ useful from the dRICH, let's store the digitized raw hits, `DRICHRawHits`, and the projected track points in the radiators, `DRICH{Aerogel,Gas}Tracks`. These will enable the usage of these production data as input to the IRT algorithm.

For each charged particle which passes through both radiators, `DRICH{Aerogel,Gas}Tracks` store 15 `TrackPoints` and the dRICH typically has less than 30 `DRICHRawHits`. We are not storing the associated `SimTrackerHits` at this time.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [x] Changes have been communicated to collaborators @chchatte92

### Does this PR introduce breaking changes? What changes might users need to make to their code?
no

### Does this PR change default behavior?
yes

### CODE REVIEW

**Comment by c-dilks** [comment]
https://github.com/eic/EICrecon/issues/564 should be tested for and/or resolved before merging.

**Comment by c-dilks** [comment]
Much pollution... 
https://github.com/eic/EICrecon/actions/runs/4905199544/jobs/8758965025?pr=655

**Comment by wdconinc** [comment]
Why does the valgrind job take so much longer than without the RICH reconstruction? Timeout after 6 hours compared to 1h23 in a [recent run](https://github.com/eic/EICrecon/actions/runs/4980543761/jobs/8913897110) is quite a difference. How does this compare in regular runtime?

**Comment by c-dilks** [comment]
> Why does the valgrind job take so much longer than without the RICH reconstruction? Timeout after 6 hours compared to 1h23 in a [recent run](https://github.com/eic/EICrecon/actions/runs/4980543761/jobs/8913897110) is quite a difference. How does this compare in regular runtime?

I haven't checked, but I suspect this is because of https://github.com/eic/EICrecon/issues/564, where tracks which don't pass through the dRICH radiators are still being run through this propagator algorithm (for a 1,000 attempts).

**Comment by c-dilks** [comment]
If we are already running this month's production, we might as well just close this PR.

**Comment by wdconinc** [comment]
If the IRT takes so long, then we need to figure out whether and how this impacts overall production for the next production campaigns too. @rahmans1 @T-Britton 

We are already concerned about the slowdown by a factor 3 compared to two months ago, and this seems like it is at least another factor 5 for reconstruction before the valgrind job times out. Part of the assessment here is to look at the call graphs from jana which the reconstruction produces (or can produce if we don't have that in the workflows here) and then looking at top consumers for common workflows, but we need to do that for an optimized build and not in valgrind's VM. This can also fall under benchmarking. @torrijeske @veprbl

**Comment by c-dilks** [comment]
This is not yet IRT code, this is input to it, in particular the track propagator. Its memory leaks should be fixed by https://github.com/eic/EICrecon/pull/656 but I need advice how to deal with #564.

**Comment by c-dilks** [comment]
Actually, let's remove the `DRICH*Tracks` collections from this, leaving only the digitizer to produce `DRICHRawHit`; valgrind should not slow down in this case, or we have issues in the digitizer...

**Comment by c-dilks** [comment]
CI valgrind check took the normal amount of time, and no issues are detected in the digitizer (`PhotoMultiplierHitDigi`).

**Pull request closed without merging**
