### PR TITLE
Add GitHub action for PR backporting

### PR DESCRIPTION
**Pull request by veprbl**
This allows one to create labels with special name like `backport v1.2` that would automatically create a PR to duplicate change into a maintenance branch.

### CODE REVIEW

**Comment by wdconinc** [comment]
Yes, thanks!!! We have needed this not just here but in eic-spack too!

**Review by wdconinc — APPROVED** [review]
Security-related questions (since `pull_request_target` with `write/write` permissions):
- who can label?
- can we block labels that refer to non-`v[0-9].[0-9]` branches?

I am trying to ensure that no external fork can create a hostile PR, label it, close it and still get stuff merged.

**Comment by veprbl** [comment]
Only org-members can apply label. The action only creates a PR after the original is merged. The backport PR is not a threat – it's not approved or merged automatically.

**Comment by veprbl** [comment]
I don't think blocking of labels is needed, it's not like incorrect labels will appear or that users can't make a PR targeting arbitrary branch. It can be done, though:
https://github.com/korthout/backport-action/blob/main/README.md#label_pattern

**Pull request merged**
