### PR TITLE
fix: use localDistXY in HcalEndcapN

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Fix the division by 0 bug #988, where segment dimensions are 0. Switched to localDistXY. Needs testing and adjustment of the max dist values.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #988)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Review by palsgit — COMMENTED** [review]
It is not working. I still see the same debug messages as before:


[EHCAL:HcalEndcapNRecHits] [warning] Unsupported segmentation type "PolarGridRPhi2"
[EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888
[EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888
[EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888
[EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888
[EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888
[EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888
[EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888

**Comment by veprbl** [comment]
> It is not working. I still see the same debug messages as before:
> 
> [EHCAL:HcalEndcapNRecHits] [warning] Unsupported segmentation type "PolarGridRPhi2" [EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888 [EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888 [EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888 [EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888 [EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888 [EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888 [EHCAL:HcalEndcapNRecHits] [debug] Using bounding box for cell dimensions: 0, 12.566370614359172, 120, 4, -0.4, 39.8862, 502.888, 0.4, 39.8862, 502.888

This is not an indicator. The hit reconstruction will still complain about the unknown segmentation upstream. What is important to check is if clustering is still using `dimScaledLocalDistXY` function that uses these values.

**Comment by lkosarz** [comment]
Does the code still crash? Without the dimScaled distance measure it shouldn't. You can also look at the size of clusters to verify which measure is used.

I see a lot of updates in 4d852a7, are they related to the fix of the problem, or just integrating unrelated changes?

**Comment by lkosarz** [comment]
Subhadip confirmed with me that the code doesn't crash anymore. So the fix solved it. I asked to check the cluster position distribution just to be sure.

**Pull request merged**
