### PR TITLE
fix: avoid division by zero by using realistic ZDC Hcal digitization

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Issue #1583 points out division by zero in cluster reconstruction. This is caused by the [term E / tE in the log-based weighting of hits](https://github.com/eic/EICrecon/blob/9d1b01ed457aa5dceb413d3dace910b2c799278b/src/algorithms/calorimetry/CalorimeterClusterRecoCoG.h#L33-L35), when [totalE is zero](https://github.com/eic/EICrecon/blob/9d1b01ed457aa5dceb413d3dace910b2c799278b/src/algorithms/calorimetry/CalorimeterClusterRecoCoG.cc#L204). That happens when the energy in a deposited hit is zero, which happens when the [raw hit amplitude is exactly equal to the pedestal](https://github.com/eic/EICrecon/blob/9d1b01ed457aa5dceb413d3dace910b2c799278b/src/algorithms/calorimetry/CalorimeterHitReco.cc#L189-L190). That can only happen [when the threshold is set below the pedestal](https://github.com/eic/EICrecon/blob/9d1b01ed457aa5dceb413d3dace910b2c799278b/src/algorithms/calorimetry/CalorimeterHitReco.cc#L172-L174), which is unphysical. 

This PR sets the threshold for the ZDC Hcal to a physical value, based on what it is set to for the ZDC Ecal. Happy to change it to something else, but we need a realistic value here.

### What kind of change does this PR introduce?
- [x] Bug fix (issue #1583)
- [ ] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Comment by wdconinc** [comment]
[HcalFarForwardZDCRecHits](https://eicrecon.epic-eic.org/pr/1593/capybara/rec_dis_18x275_minQ2=0_craterlake/index.html#HcalFarForwardZDCRecHits) are much reduced in the low energy bins, and uniformly suppressed in other variables.
image

[HcalFarForwardZDCClusters](https://eicrecon.epic-eic.org/pr/1593/capybara/rec_dis_18x275_minQ2=0_craterlake/index.html#HcalFarForwardZDCClusters) show hardly any change in the overall distributions or number of clusters.
image

**Comment by wdconinc** [comment]
Note that the decrease of the number of hits (with low energy) will in itself cause the ZDC clustering to improve in speed...

**Comment by wdconinc** [comment]
@sebouh137 Can you provide more realistic ZDC Hcal digitization parameters?

**Comment by sebouh137** [comment]
> @sebouh137 Can you provide more realistic ZDC Hcal digitization parameters?

I am going to defer this question to @rymilton , as i think he'd know the answer to that question

**Comment by sebouh137** [comment]
> > @sebouh137 Can you provide more realistic ZDC Hcal digitization parameters?
> 
> I am going to defer this question to @rymilton , as i think he'd know the answer to that question
I talked to Ryan, and he doesn't know either, and I think these values were copied from somewhere else (probably from the insert, which was copied from the FHCAL)

**Comment by wdconinc** [comment]
So you're ok with the values I changed it into?

**Comment by wdconinc** [comment]
I used your methodology and copied it from the EcalFarForwardZDCRecHits :-P

**Comment by rymilton** [comment]
As far as I know, the ZDC Hcal digitization parameters were originally taken from the insert/forward Hcal parameters at the time and then adjusted based on the performance we were getting. But I'm not sure where the -100 threshold value came from since I wasn't involved with this optimization. If the numbers you put @wdconinc fix the issue, I say go for it. We can adjust them later if need be.

**Comment by rymilton** [comment]
Do you agree @sebouh137?

**Review by veprbl — APPROVED** [review]

**Pull request merged**
