### PR TITLE
ci: asan with better symbolizer

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
This will/should/may add line numbers to the address sanitizer leak output.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Review by veprbl — APPROVED** [review]

**Comment by wdconinc** [comment]
The intention here is to address frames 3 and higher in e.g. https://github.com/eic/EICrecon/actions/runs/5457798369/jobs/9932530349#step:5:1883, since it seems none of the factory plugins get line number info.
```console
Direct leak of 211200 byte(s) in 26400 object(s) allocated from:
    #0 0x7f8dc17704c8 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x7f8dbac9cfa9 in CalorimeterHitDigi::single_hits_digi() /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterHitDigi.cc:174
    #2 0x7f8dbaca064f in CalorimeterHitDigi::AlgorithmProcess() /home/runner/work/EICrecon/EICrecon/src/algorithms/calorimetry/CalorimeterHitDigi.cc:129
    #3 0x7f8db96d3b11 in RawCalorimeterHit_factory_EcalBarrelSciGlassRawHits::Process(std::shared_ptr<JEvent const> const&) (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/BEMC.so+0xe7b11)
    #4 0x7f8db99916b3 in eicrecon::JFactoryPodioT<edm4hep::RawCalorimeterHit>::Create(std::shared_ptr<JEvent const> const&) (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/EEMC.so+0x786b3)
    #5 0x7f8db99b5a05 in std::vector<edm4hep::RawCalorimeterHit const*, std::allocator<edm4hep::RawCalorimeterHit const*> > JEvent::Get<edm4hep::RawCalorimeterHit>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/EEMC.so+0x9ca05)
    #6 0x7f8db96d6abb in CalorimeterHit_factory_EcalBarrelSciGlassRecHits::Process(std::shared_ptr<JEvent const> const&) (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/BEMC.so+0xeaabb)
    #7 0x7f8db9995aab in eicrecon::JFactoryPodioT<edm4eic::CalorimeterHit>::Create(std::shared_ptr<JEvent const> const&) (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/EEMC.so+0x7caab)
    #8 0x7f8db99b7d99 in std::vector<edm4eic::CalorimeterHit const*, std::allocator<edm4eic::CalorimeterHit const*> > JEvent::Get<edm4eic::CalorimeterHit>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/EEMC.so+0x9ed99)
    #9 0x7f8db96d9775 in ProtoCluster_factory_EcalBarrelSciGlassProtoClusters::Process(std::shared_ptr<JEvent const> const&) (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/BEMC.so+0xed775)
    #10 0x7f8db999a1bb in eicrecon::JFactoryPodioT<edm4eic::ProtoCluster>::Create(std::shared_ptr<JEvent const> const&) (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/EEMC.so+0x811bb)
    #11 0x7f8dba54c2ff in JEvent::GetCollectionBase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) const (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/digi.so+0x442ff)
    #12 0x7f8db97683f2 in eicrecon::CalorimeterClusterRecoCoG_factoryT<eicrecon::Cluster_factory_EcalBarrelSciGlassClusters>::Process(std::shared_ptr<JEvent const> const&) (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/BEMC.so+0x17c3f2)
    #13 0x7f8db996129a in JMultifactoryHelperPodio<edm4eic::MCRecoClusterParticleAssociation>::Process(std::shared_ptr<JEvent const> const&) (/home/runner/work/EICrecon/EICrecon/lib/EICrecon/plugins/EEMC.so+0x4829a)
    #14 0x7f8dc15bbd97 in JFactory::Create(std::shared_ptr<JEvent const> const&) (/usr/local/lib/libJANA.so+0x59d97)
```

**Comment by wdconinc** [comment]
However, adding the explicit symbolizer doesn't seem to do anything about this...

**Comment by veprbl** [comment]
No debug symbols in the first place?

**Comment by wdconinc** [comment]
> No debug symbols in the first place?

Maybe then the question is actually why we get proper symbols in the algorithms code when we are running this with a Release build type...

**Comment by wdconinc** [comment]
This never did what I hoped it would do... Closing.

**Pull request closed without merging**
