### PR TITLE
feat: use logger service that comes with algorithms

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Instead of giving each algorithm an spdlog logger (`m_log`), the algorithms interface provides a centralized logger service with both stream and call interfaces (`error() << msg << endmsg` and `error(msg)`). This directs the CalorimeterClusterRecoCoG and other calorimeter algorithm to use this interface.

TODO:
- [x] depends on https://github.com/eic/algorithms/pull/13
- [x] depends on https://github.com/eic/algorithms/pull/15
- [x] will conflict with https://github.com/eic/EICrecon/pull/1194

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [x] New feature (issue #__)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No.

### Does this PR change default behavior?
No.

### CODE REVIEW

**Review by veprbl — DISMISSED** [review]

**Comment by wdconinc** [comment]
Rebased, conflicts resolved.

**Review by veprbl — DISMISSED** [review]
Diff LGTM, compiles

**Review by veprbl — DISMISSED** [review]
Diff LGTM

**Comment by wdconinc** [comment]
I guess iwyu got into an instability in https://github.com/eic/EICrecon/actions/runs/7413827274/job/20174839786 ... Probably should build in a loop breakout counter or something.

**Review by veprbl — DISMISSED** [review]

**Comment by wdconinc** [comment]
This will need #1195.

**Comment by wdconinc** [comment]
Well, it works now, but it won't use the Log_service from EICrecon and it will ignore log level parameters passed on CLI.

**Comment by wdconinc** [comment]
Fails to build because (in a surprise) the juggler external/algorithms get installed and picked up, not the github.com/eic/algorithms...

**Comment by wdconinc** [comment]
This now builds on #1195 and uses the Log_service to keep track of and hand out loggers by name.

**Comment by wdconinc** [comment]
This now works using the `AlgorithmsInit_service`. The CI doesn't quite test everything, but:
- it uses the Log_service (verified by changing the Log_services format string to start with `==`),
- it respects the flags like `-PBEMC:EcalBarrelScFiClusters:LogLevel=trace`,
- it now prints e.g. `Initializing algorithms::LogSvc logger BEMC:EcalBarrelScFiClusters` when a new logger is created,
- `algorithms::LogSvc` is always initialized first, and the other `algorithms::` services can also use their own `Log_service` logger now instead of using the one from `AlgorithmsInit_service`.

```
[ServiceSvc] [info] Initializing algorithms::LogSvc logger BEMC:EcalBarrelScFiProtoClusters
[BEMC:EcalBarrelScFiProtoClusters] [info] Clustering uses localDistXZ with distances <= [40,40]
[BEMC:EcalBarrelScFiProtoClusters] [info] Using clustering method: localDistXZ
[ServiceSvc] [info] Initializing algorithms::LogSvc logger BEMC:EcalBarrelScFiRecHits
[BEMC:EcalBarrelScFiRecHits] [warning] Unsupported segmentation type "CartesianStripZ"
[ServiceSvc] [info] Initializing algorithms::LogSvc logger BEMC:EcalBarrelScFiClusters
[BEMC:EcalBarrelScFiClusters] [debug] hit size = 97
[BEMC:EcalBarrelScFiClusters] [debug] hit energy = 0.06103465 hit weight: 1
[BEMC:EcalBarrelScFiClusters] [debug] hit energy = 0.10950334 hit weight: 1
[BEMC:EcalBarrelScFiClusters] [debug] hit energy = 0.09873252 hit weight: 1
```

**Comment by wdconinc** [comment]
The lines `Initializing algorithms::LogSvc logger BEMC:EcalBarrelScFiClusters` should probably be `debug`.

**Comment by wdconinc** [comment]
Still no diffs. This is ready to merge.

**Pull request merged**
